### ISSUE TITLE
Wrong type returned by createCompletion?

### ISSUE THREAD

**Issue by dxrsz** [load1n9/openai#1]
Hello there. Thanks for sharing this library.

I believe the return types for the methods in this library are incorrect. For example, [createCompletion](https://github.com/load1n9/openai/blob/master/src/openai.ts#L8) is declared as returning `Promise<Response>`, when it's really returning a promised `response.json()`, which is of `any` type, since it's the actual response body data parsed as JSON into an object (see [here](https://deno.com/deploy/docs/runtime-response#methods)).

I think, instead, it should either be declared as returning `Promise<any>` or return `Promise<the actual object shape>` (shapes are documented [here](thebeta.openai.com/docs/api-reference/completions/create)). If you would prefer, I could contribute this change. If so, just let me know if you would prefer `Promise<any>` or if I should fully type the API.

**Comment by lino-levan** [comment]
Fixed by #2
