### ISSUE TITLE
Implement streaming API

### ISSUE THREAD

**Issue by lino-levan** [load1n9/openai#13]
This uses `EventSource`, so we'll probably have to use Skye's polyfill until https://github.com/denoland/deno/pull/14730 lands.

**Comment by daimajia** [comment]
Hi @lino-levan Thanks for your working on this project. About the `EventSource`, do this [https://deno.land/x/eventsource@v0.0.3](https://deno.land/x/eventsource@v0.0.3) project works in api streaming? 

update: i get it. we are saying the same thing. Looking forward to supporting streaming api.

**Comment by ChuckJonas** [comment]
In the meantime, maybe consider removing the "stream" option from the API interface?  

Just wasted quite a bit of time thinking my code handling the stream was buggy, when really this library just crashes if you set `stream:true` in the options...

**Comment by ChuckJonas** [comment]
In the meantime, maybe consider removing the "stream" option from the API interface?  

Just wasted quite a bit of time thinking my code handling the stream was buggy, when really this library just crashes if you set `stream:true` in the options...

**Comment by lino-levan** [comment]
I'll make a PR today. Sorry for the trouble!

**Comment by daimajia** [comment]
> 

How is the progress?

**Comment by lino-levan** [comment]
Sorry for the delay, didn't get around to doing it yesterday. PR is open now, waiting on a review from @load1n9 to merge.
