### ISSUE TITLE
Function example model should be updated

### ISSUE THREAD

**Issue by rpggio** [load1n9/openai#22]
In the [function calling example](https://github.com/load1n9/openai/blob/main/examples/chatCompletionFunction.ts), the model should be updated to `gpt-3.5-turbo-0613`.

**Comment by lino-levan** [comment]
Could you provide more context? The code is working on my end.

**Comment by rpggio** [comment]
Is a function call response returned, or just a textual response? At the time function calling was released, only the 0613 models included function calling.

> Developers can now describe functions to gpt-4-0613 and gpt-3.5-turbo-0613, and have the model intelligently choose to output a JSON object containing arguments to call those functions. This is a new way to more reliably connect GPT's capabilities with external tools and APIs.

**Comment by lino-levan** [comment]
A function call response is being returned. I believe `gpt-3.5-turbo` is just an alias for the latest stable version of the model (which would be `gpt-3.5.turbo-0613` as of today).

**Comment by raygao** [comment]
Please find the result running app at: https://comfortable-hawk-99.deno.dev/ 
Thanks a lot for your support. Appreciate it.
