### ISSUE TITLE
ChatCompletionMessage union types dissallow proper FunctionAwareAssistantCompletionMessage and AssistantCompletionMessage usage

### ISSUE THREAD

**Issue by MikP0** [load1n9/openai#24]
When passing `function` and `function_call` to the `createChatCompletion()` we should expect to have `function_call` object inside `content` of a message, however it's impossible to determine whether the openAI response is `AssistantCompletionMessage` or `FunctionAwareAssistantCompletionMessage` as both share the same `role`:

```TS
interface AssistantCompletionMessage {
  content: string;
  name?: string;
  role: "assistant";
}

interface FunctionAwareAssistantCompletionMessage {
  content: string | null;
  role: "assistant";
  function_call?: {
    "name": string;
    "arguments": string;
  };
}
```
And it seems impossible to narrow the type from that point, so properties `name` from `AssistantCompletionMessage` and property `function_call` from `FunctionAwareAssistantCompletionMessage` can't be accessed.
![image](https://github.com/load1n9/openai/assets/36931484/36eddb52-28c7-4670-9c62-d8e010615984)

Moreover, those types are not exported, so you can't really create a Type Guard yourself.

**Comment by lino-levan** [comment]
You should be able to narrow the type further by checking of the object has a key. I'm away from my computer at the moment but something like
```ts
if ("function_call" in completionMessage) {

}
```

We should probably export the types anyways though.

**Comment by MikP0** [comment]
That's a great point, thanks @lino-levan ! I have created a Pull Request with the exports - if you're interested https://github.com/load1n9/openai/pull/25
