### ISSUE TITLE
Export ChatCompletionMessage types

### ISSUE THREAD

**Issue by alexewerlof** [load1n9/openai#30]
Currently only `ChatCompletionMessage` is exported.

I need its variations to write guard type guards:

- `SystemCompletionMessage`
- `UserCompletionMessage`
- `FunctionAwareAssistantCompletionMessage`
- `FunctionCompletionMessage`
- `AssistantCompletionMessage`

1. Would you be open to a PR that addresses that?
2. Would you like me to also submit the guard functions (they help when going through the array of messages trying to identify what type each message has. e.g. a `function_call` and regular `content` both can have `role: 'assistant`, so one needs to look inside the object)?

**Comment by lino-levan** [comment]
Would be more than willing to accept the first one, the second one would be interesting, but I'd need to see more. I'd open these as two seperate PRs.

**Comment by alexewerlof** [comment]
#25 did 1. But it's not released yet. Could we release it please?

I can propose a PR for the second one but it's going to add a bit of code for type checking the JSON. I have created [JTY](https://github.com/userpixel/jty) for cases like this, but I don't want to add a dependency just for that. So before spending further time into a PR, I have a few questions:

1. Is it valuable to add type-guards to this lib? My use case is that as I go through the array of messages, I'd like to know which type each element is, and using type guards in Deno makes it easier to work in an IDE for example. Not sure how many others need this functionality.
2. If the answer is positive, do you have a special preference for how to check the shape of the JSON elements? I am new to Deno (but not new to TS/JS). I can't see a similar functionality in [STD](https://deno.land/std@0.204.0?doc) which makes me think we either have to write the basic type checking functionality in this module or use a dependency.

**Comment by alexewerlof** [comment]
Closing this as it duplicates #24.

Opened a new issue for the type guard part: #32
