### ISSUE TITLE
Add formatting to the deno.json file

### ISSUE THREAD

**Issue by alexewerlof** [load1n9/openai#33]
Why? To make `deno fmt` work as well as IDE-specific auto formatting features.

Suggestion based on the current coding style:

```json
  "fmt": {
    "indentWidth": 2,
    "semiColons": true,
    "singleQuote": false,
    "useTabs": false
  }
```

Running this against the current code base shows minimal changes (only dangling commas are added in ts files) as well as a double quote usage in the README.

Happy to do a PR if needed.

**Comment by lino-levan** [comment]
Oh, this should actually all be formatted using the default Deno settings. Feel free to submit a PR (without the fmt config) which is just formatting changes.

**Comment by alexewerlof** [comment]
fair enough. I'll do when I get some time.
